#!/usr/bin/env python3

"""
Pandoc filter to process code blocks with class "graphviz" into
graphviz-generated images.

Needs pygraphviz
"""

import os
import sys

try:
    import pygraphviz
except ImportError:
    pass
import requests

from pandocfilters import toJSONFilter, Para, Plain, Image, get_filename4code, get_caption, get_extension, get_value

# pandocfilters does not have Figure in versions < 1.5.0 which is needed to add captions
# so we define a fallback here
try:
    from pandocfilters import Figure
except ImportError:
    # pandocfilters version < 1.5.0
    sys.stderr.write("pandocfilters version < 1.5.0 detected, captions for graphviz images will not be supported.\n")
    Figure = None

def graphviz(key, value, format, _):
    if key == 'CodeBlock':
        [[ident, classes, keyvals], code] = value
        if "graphviz" in classes:
            caption, typef, keyvals = get_caption(keyvals)
            prog, keyvals = get_value(keyvals, u"prog", u"dot")
            filetype = get_extension(format, "png", beamer="pdf", html="svg", latex="pdf")
            dest = get_filename4code("graphviz", code, filetype)

            if not os.path.isfile(dest):
                # assuming that the specified program is installed and in PATH
                if "pygraphviz" in globals():
                    try:
                        g = pygraphviz.AGraph(string=code)
                        g.layout()
                        g.draw(dest, prog=prog)
                        sys.stderr.write(f'Created image {dest}\n')
                    except pygraphviz.DotError as e:
                        sys.stderr.write(f"Error creating graphviz image: {e}\n")
                        sys.stderr.write(code)
                        sys.exit(1)
                # otherwise using quickchart.io api
                else:
                    url = f"https://quickchart.io/graphviz?format={requests.utils.quote(filetype)}&graph={requests.utils.quote(code)}"
                    response = requests.get(url)
                    with open(dest, "wb") as f:
                        f.write(response.content)
                    sys.stderr.write(f'Created image using quickchart.io {dest}\n')

            # see https://github.com/jgm/pandocfilters/commit/9988f9a6e4528d2ce3c4b885b8eed9328c3b408a
            if caption and Figure is not None:
                 return Figure(["",[],[]],
                               [None,[Para(caption)]],
                               [Plain([Image([ident, [], keyvals], caption, [dest, typef])])])

            return Para([Image([ident, [], keyvals], caption, [dest, typef])])
            

if __name__ == "__main__":
    toJSONFilter(graphviz)