#!/usr/bin/env python3

"""
Pandoc filter to filter out elements with a specific class.

For example...

    pandoc -t json | python3 pandoc-classfilter myclass | pandoc


Needs pandocfilers
"""

import os
import sys

from PIL import Image as PILImage

from pandocfilters import toJSONFilter, Str

def classfilter(key, value, format, meta):
    if key == 'Div':
        [[ident, classes, kvs], contents] = value

        if 'notes' in classes:
            return []

if __name__ == "__main__":
    toJSONFilter(classfilter)