#!/usr/bin/env python3

"""
Pandoc filter to filter out elements with a specific class.

For example...

    pandoc -t json | python3 pandoc-classfilter myclass | pandoc


Needs pandocfilers
"""

import os
import sys


from pandocfilters import toJSONFilter, Str


def attribution(key, value, format, meta):
    if key == 'Div':
        [[ident, classes, kvs], contents] = value
        
        if 'attribution' not in classes: return

        if format == 'html':
            return # todo
        elif format in ('latex', 'beamer'):
            return [{'t': 'Plain', 'c': [
                        {'t': 'RawInline', 'c': ['tex', '{ \\flushright ']}, 
                        {'t': 'RawInline', 'c': ['tex', '\\tiny ']}]}] +  \
                    contents + \
                    [{'t': 'Plain', 'c': [
                        {'t': 'RawInline', 'c': ['tex', '} ']}]}]


            
        
            print( key, file=sys.stderr )
            print( ident, file=sys.stderr )
            print( classes, file=sys.stderr )
            print( kvs, file=sys.stderr )
            print( contents, file=sys.stderr )
            print( format, file=sys.stderr )
            #print( meta, file=sys.stderr)
            return []

if __name__ == "__main__":
    toJSONFilter(attribution)